//package com.edexsoft.matrix.domain;
//
//import java.util.ArrayList;
//import java.util.Date;
//import java.util.List;
//
//public class UserExample {
//    /**
//	 * This field was generated by MyBatis Generator. This field corresponds to the database table t_user
//	 * @mbg.generated
//	 */
//	protected String orderByClause;
//
//	/**
//	 * This field was generated by MyBatis Generator. This field corresponds to the database table t_user
//	 * @mbg.generated
//	 */
//	protected boolean distinct;
//
//	/**
//	 * This field was generated by MyBatis Generator. This field corresponds to the database table t_user
//	 * @mbg.generated
//	 */
//	protected List<Criteria> oredCriteria;
//
//	private Long limit;
//
//	private Long offset;
//
//	/**
//	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_user
//	 * @mbg.generated
//	 */
//	public UserExample() {
//		oredCriteria = new ArrayList<Criteria>();
//	}
//
//	/**
//	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_user
//	 * @mbg.generated
//	 */
//	public void setOrderByClause(String orderByClause) {
//		this.orderByClause = orderByClause;
//	}
//
//	/**
//	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_user
//	 * @mbg.generated
//	 */
//	public String getOrderByClause() {
//		return orderByClause;
//	}
//
//	/**
//	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_user
//	 * @mbg.generated
//	 */
//	public void setDistinct(boolean distinct) {
//		this.distinct = distinct;
//	}
//
//	/**
//	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_user
//	 * @mbg.generated
//	 */
//	public boolean isDistinct() {
//		return distinct;
//	}
//
//	/**
//	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_user
//	 * @mbg.generated
//	 */
//	public List<Criteria> getOredCriteria() {
//		return oredCriteria;
//	}
//
//	/**
//	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_user
//	 * @mbg.generated
//	 */
//	public void or(Criteria criteria) {
//		oredCriteria.add(criteria);
//	}
//
//	/**
//	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_user
//	 * @mbg.generated
//	 */
//	public Criteria or() {
//		Criteria criteria = createCriteriaInternal();
//		oredCriteria.add(criteria);
//		return criteria;
//	}
//
//	/**
//	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_user
//	 * @mbg.generated
//	 */
//	public Criteria createCriteria() {
//		Criteria criteria = createCriteriaInternal();
//		if (oredCriteria.size() == 0) {
//			oredCriteria.add(criteria);
//		}
//		return criteria;
//	}
//
//	/**
//	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_user
//	 * @mbg.generated
//	 */
//	protected Criteria createCriteriaInternal() {
//		Criteria criteria = new Criteria();
//		return criteria;
//	}
//
//	/**
//	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_user
//	 * @mbg.generated
//	 */
//	public void clear() {
//		oredCriteria.clear();
//		orderByClause = null;
//		distinct = false;
//	}
//
//	public void setLimit(Long limit) {
//		this.limit = limit;
//	}
//
//	public Long getLimit() {
//		return limit;
//	}
//
//	public void setOffset(Long offset) {
//		this.offset = offset;
//	}
//
//	public Long getOffset() {
//		return offset;
//	}
//
//	/**
//	 * This class was generated by MyBatis Generator. This class corresponds to the database table t_user
//	 * @mbg.generated
//	 */
//	protected abstract static class GeneratedCriteria {
//		protected List<Criterion> criteria;
//
//		protected GeneratedCriteria() {
//			super();
//			criteria = new ArrayList<Criterion>();
//		}
//
//		public boolean isValid() {
//			return criteria.size() > 0;
//		}
//
//		public List<Criterion> getAllCriteria() {
//			return criteria;
//		}
//
//		public List<Criterion> getCriteria() {
//			return criteria;
//		}
//
//		protected void addCriterion(String condition) {
//			if (condition == null) {
//				throw new RuntimeException("Value for condition cannot be null");
//			}
//			criteria.add(new Criterion(condition));
//		}
//
//		protected void addCriterion(String condition, Object value, String property) {
//			if (value == null) {
//				throw new RuntimeException("Value for " + property + " cannot be null");
//			}
//			criteria.add(new Criterion(condition, value));
//		}
//
//		protected void addCriterion(String condition, Object value1, Object value2, String property) {
//			if (value1 == null || value2 == null) {
//				throw new RuntimeException("Between values for " + property + " cannot be null");
//			}
//			criteria.add(new Criterion(condition, value1, value2));
//		}
//
//		public Criteria andIdIsNull() {
//			addCriterion("id is null");
//			return (Criteria) this;
//		}
//
//		public Criteria andIdIsNotNull() {
//			addCriterion("id is not null");
//			return (Criteria) this;
//		}
//
//		public Criteria andIdEqualTo(Long value) {
//			addCriterion("id =", value, "id");
//			return (Criteria) this;
//		}
//
//		public Criteria andIdNotEqualTo(Long value) {
//			addCriterion("id <>", value, "id");
//			return (Criteria) this;
//		}
//
//		public Criteria andIdGreaterThan(Long value) {
//			addCriterion("id >", value, "id");
//			return (Criteria) this;
//		}
//
//		public Criteria andIdGreaterThanOrEqualTo(Long value) {
//			addCriterion("id >=", value, "id");
//			return (Criteria) this;
//		}
//
//		public Criteria andIdLessThan(Long value) {
//			addCriterion("id <", value, "id");
//			return (Criteria) this;
//		}
//
//		public Criteria andIdLessThanOrEqualTo(Long value) {
//			addCriterion("id <=", value, "id");
//			return (Criteria) this;
//		}
//
//		public Criteria andIdIn(List<Long> values) {
//			addCriterion("id in", values, "id");
//			return (Criteria) this;
//		}
//
//		public Criteria andIdNotIn(List<Long> values) {
//			addCriterion("id not in", values, "id");
//			return (Criteria) this;
//		}
//
//		public Criteria andIdBetween(Long value1, Long value2) {
//			addCriterion("id between", value1, value2, "id");
//			return (Criteria) this;
//		}
//
//		public Criteria andIdNotBetween(Long value1, Long value2) {
//			addCriterion("id not between", value1, value2, "id");
//			return (Criteria) this;
//		}
//
//		public Criteria andAccountIsNull() {
//			addCriterion("account is null");
//			return (Criteria) this;
//		}
//
//		public Criteria andAccountIsNotNull() {
//			addCriterion("account is not null");
//			return (Criteria) this;
//		}
//
//		public Criteria andAccountEqualTo(String value) {
//			addCriterion("account =", value, "account");
//			return (Criteria) this;
//		}
//
//		public Criteria andAccountNotEqualTo(String value) {
//			addCriterion("account <>", value, "account");
//			return (Criteria) this;
//		}
//
//		public Criteria andAccountGreaterThan(String value) {
//			addCriterion("account >", value, "account");
//			return (Criteria) this;
//		}
//
//		public Criteria andAccountGreaterThanOrEqualTo(String value) {
//			addCriterion("account >=", value, "account");
//			return (Criteria) this;
//		}
//
//		public Criteria andAccountLessThan(String value) {
//			addCriterion("account <", value, "account");
//			return (Criteria) this;
//		}
//
//		public Criteria andAccountLessThanOrEqualTo(String value) {
//			addCriterion("account <=", value, "account");
//			return (Criteria) this;
//		}
//
//		public Criteria andAccountLike(String value) {
//			addCriterion("account like", value, "account");
//			return (Criteria) this;
//		}
//
//		public Criteria andAccountNotLike(String value) {
//			addCriterion("account not like", value, "account");
//			return (Criteria) this;
//		}
//
//		public Criteria andAccountIn(List<String> values) {
//			addCriterion("account in", values, "account");
//			return (Criteria) this;
//		}
//
//		public Criteria andAccountNotIn(List<String> values) {
//			addCriterion("account not in", values, "account");
//			return (Criteria) this;
//		}
//
//		public Criteria andAccountBetween(String value1, String value2) {
//			addCriterion("account between", value1, value2, "account");
//			return (Criteria) this;
//		}
//
//		public Criteria andAccountNotBetween(String value1, String value2) {
//			addCriterion("account not between", value1, value2, "account");
//			return (Criteria) this;
//		}
//
//		public Criteria andPasswordIsNull() {
//			addCriterion("password is null");
//			return (Criteria) this;
//		}
//
//		public Criteria andPasswordIsNotNull() {
//			addCriterion("password is not null");
//			return (Criteria) this;
//		}
//
//		public Criteria andPasswordEqualTo(String value) {
//			addCriterion("password =", value, "password");
//			return (Criteria) this;
//		}
//
//		public Criteria andPasswordNotEqualTo(String value) {
//			addCriterion("password <>", value, "password");
//			return (Criteria) this;
//		}
//
//		public Criteria andPasswordGreaterThan(String value) {
//			addCriterion("password >", value, "password");
//			return (Criteria) this;
//		}
//
//		public Criteria andPasswordGreaterThanOrEqualTo(String value) {
//			addCriterion("password >=", value, "password");
//			return (Criteria) this;
//		}
//
//		public Criteria andPasswordLessThan(String value) {
//			addCriterion("password <", value, "password");
//			return (Criteria) this;
//		}
//
//		public Criteria andPasswordLessThanOrEqualTo(String value) {
//			addCriterion("password <=", value, "password");
//			return (Criteria) this;
//		}
//
//		public Criteria andPasswordLike(String value) {
//			addCriterion("password like", value, "password");
//			return (Criteria) this;
//		}
//
//		public Criteria andPasswordNotLike(String value) {
//			addCriterion("password not like", value, "password");
//			return (Criteria) this;
//		}
//
//		public Criteria andPasswordIn(List<String> values) {
//			addCriterion("password in", values, "password");
//			return (Criteria) this;
//		}
//
//		public Criteria andPasswordNotIn(List<String> values) {
//			addCriterion("password not in", values, "password");
//			return (Criteria) this;
//		}
//
//		public Criteria andPasswordBetween(String value1, String value2) {
//			addCriterion("password between", value1, value2, "password");
//			return (Criteria) this;
//		}
//
//		public Criteria andPasswordNotBetween(String value1, String value2) {
//			addCriterion("password not between", value1, value2, "password");
//			return (Criteria) this;
//		}
//
//		public Criteria andNickNameIsNull() {
//			addCriterion("nick_name is null");
//			return (Criteria) this;
//		}
//
//		public Criteria andNickNameIsNotNull() {
//			addCriterion("nick_name is not null");
//			return (Criteria) this;
//		}
//
//		public Criteria andNickNameEqualTo(String value) {
//			addCriterion("nick_name =", value, "nickName");
//			return (Criteria) this;
//		}
//
//		public Criteria andNickNameNotEqualTo(String value) {
//			addCriterion("nick_name <>", value, "nickName");
//			return (Criteria) this;
//		}
//
//		public Criteria andNickNameGreaterThan(String value) {
//			addCriterion("nick_name >", value, "nickName");
//			return (Criteria) this;
//		}
//
//		public Criteria andNickNameGreaterThanOrEqualTo(String value) {
//			addCriterion("nick_name >=", value, "nickName");
//			return (Criteria) this;
//		}
//
//		public Criteria andNickNameLessThan(String value) {
//			addCriterion("nick_name <", value, "nickName");
//			return (Criteria) this;
//		}
//
//		public Criteria andNickNameLessThanOrEqualTo(String value) {
//			addCriterion("nick_name <=", value, "nickName");
//			return (Criteria) this;
//		}
//
//		public Criteria andNickNameLike(String value) {
//			addCriterion("nick_name like", value, "nickName");
//			return (Criteria) this;
//		}
//
//		public Criteria andNickNameNotLike(String value) {
//			addCriterion("nick_name not like", value, "nickName");
//			return (Criteria) this;
//		}
//
//		public Criteria andNickNameIn(List<String> values) {
//			addCriterion("nick_name in", values, "nickName");
//			return (Criteria) this;
//		}
//
//		public Criteria andNickNameNotIn(List<String> values) {
//			addCriterion("nick_name not in", values, "nickName");
//			return (Criteria) this;
//		}
//
//		public Criteria andNickNameBetween(String value1, String value2) {
//			addCriterion("nick_name between", value1, value2, "nickName");
//			return (Criteria) this;
//		}
//
//		public Criteria andNickNameNotBetween(String value1, String value2) {
//			addCriterion("nick_name not between", value1, value2, "nickName");
//			return (Criteria) this;
//		}
//
//		public Criteria andAuditStateIsNull() {
//			addCriterion("audit_state is null");
//			return (Criteria) this;
//		}
//
//		public Criteria andAuditStateIsNotNull() {
//			addCriterion("audit_state is not null");
//			return (Criteria) this;
//		}
//
//		public Criteria andAuditStateEqualTo(Integer value) {
//			addCriterion("audit_state =", value, "auditState");
//			return (Criteria) this;
//		}
//
//		public Criteria andAuditStateNotEqualTo(Integer value) {
//			addCriterion("audit_state <>", value, "auditState");
//			return (Criteria) this;
//		}
//
//		public Criteria andAuditStateGreaterThan(Integer value) {
//			addCriterion("audit_state >", value, "auditState");
//			return (Criteria) this;
//		}
//
//		public Criteria andAuditStateGreaterThanOrEqualTo(Integer value) {
//			addCriterion("audit_state >=", value, "auditState");
//			return (Criteria) this;
//		}
//
//		public Criteria andAuditStateLessThan(Integer value) {
//			addCriterion("audit_state <", value, "auditState");
//			return (Criteria) this;
//		}
//
//		public Criteria andAuditStateLessThanOrEqualTo(Integer value) {
//			addCriterion("audit_state <=", value, "auditState");
//			return (Criteria) this;
//		}
//
//		public Criteria andAuditStateIn(List<Integer> values) {
//			addCriterion("audit_state in", values, "auditState");
//			return (Criteria) this;
//		}
//
//		public Criteria andAuditStateNotIn(List<Integer> values) {
//			addCriterion("audit_state not in", values, "auditState");
//			return (Criteria) this;
//		}
//
//		public Criteria andAuditStateBetween(Integer value1, Integer value2) {
//			addCriterion("audit_state between", value1, value2, "auditState");
//			return (Criteria) this;
//		}
//
//		public Criteria andAuditStateNotBetween(Integer value1, Integer value2) {
//			addCriterion("audit_state not between", value1, value2, "auditState");
//			return (Criteria) this;
//		}
//
//		public Criteria andDescIsNull() {
//			addCriterion("desc is null");
//			return (Criteria) this;
//		}
//
//		public Criteria andDescIsNotNull() {
//			addCriterion("desc is not null");
//			return (Criteria) this;
//		}
//
//		public Criteria andDescEqualTo(String value) {
//			addCriterion("desc =", value, "desc");
//			return (Criteria) this;
//		}
//
//		public Criteria andDescNotEqualTo(String value) {
//			addCriterion("desc <>", value, "desc");
//			return (Criteria) this;
//		}
//
//		public Criteria andDescGreaterThan(String value) {
//			addCriterion("desc >", value, "desc");
//			return (Criteria) this;
//		}
//
//		public Criteria andDescGreaterThanOrEqualTo(String value) {
//			addCriterion("desc >=", value, "desc");
//			return (Criteria) this;
//		}
//
//		public Criteria andDescLessThan(String value) {
//			addCriterion("desc <", value, "desc");
//			return (Criteria) this;
//		}
//
//		public Criteria andDescLessThanOrEqualTo(String value) {
//			addCriterion("desc <=", value, "desc");
//			return (Criteria) this;
//		}
//
//		public Criteria andDescLike(String value) {
//			addCriterion("desc like", value, "desc");
//			return (Criteria) this;
//		}
//
//		public Criteria andDescNotLike(String value) {
//			addCriterion("desc not like", value, "desc");
//			return (Criteria) this;
//		}
//
//		public Criteria andDescIn(List<String> values) {
//			addCriterion("desc in", values, "desc");
//			return (Criteria) this;
//		}
//
//		public Criteria andDescNotIn(List<String> values) {
//			addCriterion("desc not in", values, "desc");
//			return (Criteria) this;
//		}
//
//		public Criteria andDescBetween(String value1, String value2) {
//			addCriterion("desc between", value1, value2, "desc");
//			return (Criteria) this;
//		}
//
//		public Criteria andDescNotBetween(String value1, String value2) {
//			addCriterion("desc not between", value1, value2, "desc");
//			return (Criteria) this;
//		}
//
//		public Criteria andExt1IsNull() {
//			addCriterion("ext_1 is null");
//			return (Criteria) this;
//		}
//
//		public Criteria andExt1IsNotNull() {
//			addCriterion("ext_1 is not null");
//			return (Criteria) this;
//		}
//
//		public Criteria andExt1EqualTo(String value) {
//			addCriterion("ext_1 =", value, "ext1");
//			return (Criteria) this;
//		}
//
//		public Criteria andExt1NotEqualTo(String value) {
//			addCriterion("ext_1 <>", value, "ext1");
//			return (Criteria) this;
//		}
//
//		public Criteria andExt1GreaterThan(String value) {
//			addCriterion("ext_1 >", value, "ext1");
//			return (Criteria) this;
//		}
//
//		public Criteria andExt1GreaterThanOrEqualTo(String value) {
//			addCriterion("ext_1 >=", value, "ext1");
//			return (Criteria) this;
//		}
//
//		public Criteria andExt1LessThan(String value) {
//			addCriterion("ext_1 <", value, "ext1");
//			return (Criteria) this;
//		}
//
//		public Criteria andExt1LessThanOrEqualTo(String value) {
//			addCriterion("ext_1 <=", value, "ext1");
//			return (Criteria) this;
//		}
//
//		public Criteria andExt1Like(String value) {
//			addCriterion("ext_1 like", value, "ext1");
//			return (Criteria) this;
//		}
//
//		public Criteria andExt1NotLike(String value) {
//			addCriterion("ext_1 not like", value, "ext1");
//			return (Criteria) this;
//		}
//
//		public Criteria andExt1In(List<String> values) {
//			addCriterion("ext_1 in", values, "ext1");
//			return (Criteria) this;
//		}
//
//		public Criteria andExt1NotIn(List<String> values) {
//			addCriterion("ext_1 not in", values, "ext1");
//			return (Criteria) this;
//		}
//
//		public Criteria andExt1Between(String value1, String value2) {
//			addCriterion("ext_1 between", value1, value2, "ext1");
//			return (Criteria) this;
//		}
//
//		public Criteria andExt1NotBetween(String value1, String value2) {
//			addCriterion("ext_1 not between", value1, value2, "ext1");
//			return (Criteria) this;
//		}
//
//		public Criteria andExt2IsNull() {
//			addCriterion("ext_2 is null");
//			return (Criteria) this;
//		}
//
//		public Criteria andExt2IsNotNull() {
//			addCriterion("ext_2 is not null");
//			return (Criteria) this;
//		}
//
//		public Criteria andExt2EqualTo(String value) {
//			addCriterion("ext_2 =", value, "ext2");
//			return (Criteria) this;
//		}
//
//		public Criteria andExt2NotEqualTo(String value) {
//			addCriterion("ext_2 <>", value, "ext2");
//			return (Criteria) this;
//		}
//
//		public Criteria andExt2GreaterThan(String value) {
//			addCriterion("ext_2 >", value, "ext2");
//			return (Criteria) this;
//		}
//
//		public Criteria andExt2GreaterThanOrEqualTo(String value) {
//			addCriterion("ext_2 >=", value, "ext2");
//			return (Criteria) this;
//		}
//
//		public Criteria andExt2LessThan(String value) {
//			addCriterion("ext_2 <", value, "ext2");
//			return (Criteria) this;
//		}
//
//		public Criteria andExt2LessThanOrEqualTo(String value) {
//			addCriterion("ext_2 <=", value, "ext2");
//			return (Criteria) this;
//		}
//
//		public Criteria andExt2Like(String value) {
//			addCriterion("ext_2 like", value, "ext2");
//			return (Criteria) this;
//		}
//
//		public Criteria andExt2NotLike(String value) {
//			addCriterion("ext_2 not like", value, "ext2");
//			return (Criteria) this;
//		}
//
//		public Criteria andExt2In(List<String> values) {
//			addCriterion("ext_2 in", values, "ext2");
//			return (Criteria) this;
//		}
//
//		public Criteria andExt2NotIn(List<String> values) {
//			addCriterion("ext_2 not in", values, "ext2");
//			return (Criteria) this;
//		}
//
//		public Criteria andExt2Between(String value1, String value2) {
//			addCriterion("ext_2 between", value1, value2, "ext2");
//			return (Criteria) this;
//		}
//
//		public Criteria andExt2NotBetween(String value1, String value2) {
//			addCriterion("ext_2 not between", value1, value2, "ext2");
//			return (Criteria) this;
//		}
//
//		public Criteria andExt3IsNull() {
//			addCriterion("ext_3 is null");
//			return (Criteria) this;
//		}
//
//		public Criteria andExt3IsNotNull() {
//			addCriterion("ext_3 is not null");
//			return (Criteria) this;
//		}
//
//		public Criteria andExt3EqualTo(String value) {
//			addCriterion("ext_3 =", value, "ext3");
//			return (Criteria) this;
//		}
//
//		public Criteria andExt3NotEqualTo(String value) {
//			addCriterion("ext_3 <>", value, "ext3");
//			return (Criteria) this;
//		}
//
//		public Criteria andExt3GreaterThan(String value) {
//			addCriterion("ext_3 >", value, "ext3");
//			return (Criteria) this;
//		}
//
//		public Criteria andExt3GreaterThanOrEqualTo(String value) {
//			addCriterion("ext_3 >=", value, "ext3");
//			return (Criteria) this;
//		}
//
//		public Criteria andExt3LessThan(String value) {
//			addCriterion("ext_3 <", value, "ext3");
//			return (Criteria) this;
//		}
//
//		public Criteria andExt3LessThanOrEqualTo(String value) {
//			addCriterion("ext_3 <=", value, "ext3");
//			return (Criteria) this;
//		}
//
//		public Criteria andExt3Like(String value) {
//			addCriterion("ext_3 like", value, "ext3");
//			return (Criteria) this;
//		}
//
//		public Criteria andExt3NotLike(String value) {
//			addCriterion("ext_3 not like", value, "ext3");
//			return (Criteria) this;
//		}
//
//		public Criteria andExt3In(List<String> values) {
//			addCriterion("ext_3 in", values, "ext3");
//			return (Criteria) this;
//		}
//
//		public Criteria andExt3NotIn(List<String> values) {
//			addCriterion("ext_3 not in", values, "ext3");
//			return (Criteria) this;
//		}
//
//		public Criteria andExt3Between(String value1, String value2) {
//			addCriterion("ext_3 between", value1, value2, "ext3");
//			return (Criteria) this;
//		}
//
//		public Criteria andExt3NotBetween(String value1, String value2) {
//			addCriterion("ext_3 not between", value1, value2, "ext3");
//			return (Criteria) this;
//		}
//
//		public Criteria andExt4IsNull() {
//			addCriterion("ext_4 is null");
//			return (Criteria) this;
//		}
//
//		public Criteria andExt4IsNotNull() {
//			addCriterion("ext_4 is not null");
//			return (Criteria) this;
//		}
//
//		public Criteria andExt4EqualTo(String value) {
//			addCriterion("ext_4 =", value, "ext4");
//			return (Criteria) this;
//		}
//
//		public Criteria andExt4NotEqualTo(String value) {
//			addCriterion("ext_4 <>", value, "ext4");
//			return (Criteria) this;
//		}
//
//		public Criteria andExt4GreaterThan(String value) {
//			addCriterion("ext_4 >", value, "ext4");
//			return (Criteria) this;
//		}
//
//		public Criteria andExt4GreaterThanOrEqualTo(String value) {
//			addCriterion("ext_4 >=", value, "ext4");
//			return (Criteria) this;
//		}
//
//		public Criteria andExt4LessThan(String value) {
//			addCriterion("ext_4 <", value, "ext4");
//			return (Criteria) this;
//		}
//
//		public Criteria andExt4LessThanOrEqualTo(String value) {
//			addCriterion("ext_4 <=", value, "ext4");
//			return (Criteria) this;
//		}
//
//		public Criteria andExt4Like(String value) {
//			addCriterion("ext_4 like", value, "ext4");
//			return (Criteria) this;
//		}
//
//		public Criteria andExt4NotLike(String value) {
//			addCriterion("ext_4 not like", value, "ext4");
//			return (Criteria) this;
//		}
//
//		public Criteria andExt4In(List<String> values) {
//			addCriterion("ext_4 in", values, "ext4");
//			return (Criteria) this;
//		}
//
//		public Criteria andExt4NotIn(List<String> values) {
//			addCriterion("ext_4 not in", values, "ext4");
//			return (Criteria) this;
//		}
//
//		public Criteria andExt4Between(String value1, String value2) {
//			addCriterion("ext_4 between", value1, value2, "ext4");
//			return (Criteria) this;
//		}
//
//		public Criteria andExt4NotBetween(String value1, String value2) {
//			addCriterion("ext_4 not between", value1, value2, "ext4");
//			return (Criteria) this;
//		}
//
//		public Criteria andMetaCreatedIsNull() {
//			addCriterion("meta_created is null");
//			return (Criteria) this;
//		}
//
//		public Criteria andMetaCreatedIsNotNull() {
//			addCriterion("meta_created is not null");
//			return (Criteria) this;
//		}
//
//		public Criteria andMetaCreatedEqualTo(Date value) {
//			addCriterion("meta_created =", value, "metaCreated");
//			return (Criteria) this;
//		}
//
//		public Criteria andMetaCreatedNotEqualTo(Date value) {
//			addCriterion("meta_created <>", value, "metaCreated");
//			return (Criteria) this;
//		}
//
//		public Criteria andMetaCreatedGreaterThan(Date value) {
//			addCriterion("meta_created >", value, "metaCreated");
//			return (Criteria) this;
//		}
//
//		public Criteria andMetaCreatedGreaterThanOrEqualTo(Date value) {
//			addCriterion("meta_created >=", value, "metaCreated");
//			return (Criteria) this;
//		}
//
//		public Criteria andMetaCreatedLessThan(Date value) {
//			addCriterion("meta_created <", value, "metaCreated");
//			return (Criteria) this;
//		}
//
//		public Criteria andMetaCreatedLessThanOrEqualTo(Date value) {
//			addCriterion("meta_created <=", value, "metaCreated");
//			return (Criteria) this;
//		}
//
//		public Criteria andMetaCreatedIn(List<Date> values) {
//			addCriterion("meta_created in", values, "metaCreated");
//			return (Criteria) this;
//		}
//
//		public Criteria andMetaCreatedNotIn(List<Date> values) {
//			addCriterion("meta_created not in", values, "metaCreated");
//			return (Criteria) this;
//		}
//
//		public Criteria andMetaCreatedBetween(Date value1, Date value2) {
//			addCriterion("meta_created between", value1, value2, "metaCreated");
//			return (Criteria) this;
//		}
//
//		public Criteria andMetaCreatedNotBetween(Date value1, Date value2) {
//			addCriterion("meta_created not between", value1, value2, "metaCreated");
//			return (Criteria) this;
//		}
//
//		public Criteria andMetaUpdatedIsNull() {
//			addCriterion("meta_updated is null");
//			return (Criteria) this;
//		}
//
//		public Criteria andMetaUpdatedIsNotNull() {
//			addCriterion("meta_updated is not null");
//			return (Criteria) this;
//		}
//
//		public Criteria andMetaUpdatedEqualTo(Date value) {
//			addCriterion("meta_updated =", value, "metaUpdated");
//			return (Criteria) this;
//		}
//
//		public Criteria andMetaUpdatedNotEqualTo(Date value) {
//			addCriterion("meta_updated <>", value, "metaUpdated");
//			return (Criteria) this;
//		}
//
//		public Criteria andMetaUpdatedGreaterThan(Date value) {
//			addCriterion("meta_updated >", value, "metaUpdated");
//			return (Criteria) this;
//		}
//
//		public Criteria andMetaUpdatedGreaterThanOrEqualTo(Date value) {
//			addCriterion("meta_updated >=", value, "metaUpdated");
//			return (Criteria) this;
//		}
//
//		public Criteria andMetaUpdatedLessThan(Date value) {
//			addCriterion("meta_updated <", value, "metaUpdated");
//			return (Criteria) this;
//		}
//
//		public Criteria andMetaUpdatedLessThanOrEqualTo(Date value) {
//			addCriterion("meta_updated <=", value, "metaUpdated");
//			return (Criteria) this;
//		}
//
//		public Criteria andMetaUpdatedIn(List<Date> values) {
//			addCriterion("meta_updated in", values, "metaUpdated");
//			return (Criteria) this;
//		}
//
//		public Criteria andMetaUpdatedNotIn(List<Date> values) {
//			addCriterion("meta_updated not in", values, "metaUpdated");
//			return (Criteria) this;
//		}
//
//		public Criteria andMetaUpdatedBetween(Date value1, Date value2) {
//			addCriterion("meta_updated between", value1, value2, "metaUpdated");
//			return (Criteria) this;
//		}
//
//		public Criteria andMetaUpdatedNotBetween(Date value1, Date value2) {
//			addCriterion("meta_updated not between", value1, value2, "metaUpdated");
//			return (Criteria) this;
//		}
//
//		public Criteria andMetaLogicFlagIsNull() {
//			addCriterion("meta_logic_flag is null");
//			return (Criteria) this;
//		}
//
//		public Criteria andMetaLogicFlagIsNotNull() {
//			addCriterion("meta_logic_flag is not null");
//			return (Criteria) this;
//		}
//
//		public Criteria andMetaLogicFlagEqualTo(Integer value) {
//			addCriterion("meta_logic_flag =", value, "metaLogicFlag");
//			return (Criteria) this;
//		}
//
//		public Criteria andMetaLogicFlagNotEqualTo(Integer value) {
//			addCriterion("meta_logic_flag <>", value, "metaLogicFlag");
//			return (Criteria) this;
//		}
//
//		public Criteria andMetaLogicFlagGreaterThan(Integer value) {
//			addCriterion("meta_logic_flag >", value, "metaLogicFlag");
//			return (Criteria) this;
//		}
//
//		public Criteria andMetaLogicFlagGreaterThanOrEqualTo(Integer value) {
//			addCriterion("meta_logic_flag >=", value, "metaLogicFlag");
//			return (Criteria) this;
//		}
//
//		public Criteria andMetaLogicFlagLessThan(Integer value) {
//			addCriterion("meta_logic_flag <", value, "metaLogicFlag");
//			return (Criteria) this;
//		}
//
//		public Criteria andMetaLogicFlagLessThanOrEqualTo(Integer value) {
//			addCriterion("meta_logic_flag <=", value, "metaLogicFlag");
//			return (Criteria) this;
//		}
//
//		public Criteria andMetaLogicFlagIn(List<Integer> values) {
//			addCriterion("meta_logic_flag in", values, "metaLogicFlag");
//			return (Criteria) this;
//		}
//
//		public Criteria andMetaLogicFlagNotIn(List<Integer> values) {
//			addCriterion("meta_logic_flag not in", values, "metaLogicFlag");
//			return (Criteria) this;
//		}
//
//		public Criteria andMetaLogicFlagBetween(Integer value1, Integer value2) {
//			addCriterion("meta_logic_flag between", value1, value2, "metaLogicFlag");
//			return (Criteria) this;
//		}
//
//		public Criteria andMetaLogicFlagNotBetween(Integer value1, Integer value2) {
//			addCriterion("meta_logic_flag not between", value1, value2, "metaLogicFlag");
//			return (Criteria) this;
//		}
//	}
//
//	/**
//	 * This class was generated by MyBatis Generator. This class corresponds to the database table t_user
//	 * @mbg.generated
//	 */
//	public static class Criterion {
//		private String condition;
//		private Object value;
//		private Object secondValue;
//		private boolean noValue;
//		private boolean singleValue;
//		private boolean betweenValue;
//		private boolean listValue;
//		private String typeHandler;
//
//		public String getCondition() {
//			return condition;
//		}
//
//		public Object getValue() {
//			return value;
//		}
//
//		public Object getSecondValue() {
//			return secondValue;
//		}
//
//		public boolean isNoValue() {
//			return noValue;
//		}
//
//		public boolean isSingleValue() {
//			return singleValue;
//		}
//
//		public boolean isBetweenValue() {
//			return betweenValue;
//		}
//
//		public boolean isListValue() {
//			return listValue;
//		}
//
//		public String getTypeHandler() {
//			return typeHandler;
//		}
//
//		protected Criterion(String condition) {
//			super();
//			this.condition = condition;
//			this.typeHandler = null;
//			this.noValue = true;
//		}
//
//		protected Criterion(String condition, Object value, String typeHandler) {
//			super();
//			this.condition = condition;
//			this.value = value;
//			this.typeHandler = typeHandler;
//			if (value instanceof List<?>) {
//				this.listValue = true;
//			} else {
//				this.singleValue = true;
//			}
//		}
//
//		protected Criterion(String condition, Object value) {
//			this(condition, value, null);
//		}
//
//		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
//			super();
//			this.condition = condition;
//			this.value = value;
//			this.secondValue = secondValue;
//			this.typeHandler = typeHandler;
//			this.betweenValue = true;
//		}
//
//		protected Criterion(String condition, Object value, Object secondValue) {
//			this(condition, value, secondValue, null);
//		}
//	}
//
//    /**
//     * This class was generated by MyBatis Generator.
//     * This class corresponds to the database table t_user
//     *
//     * @mbg.generated do_not_delete_during_merge
//     */
//    public static class Criteria extends GeneratedCriteria {
//
//        protected Criteria() {
//            super();
//        }
//    }
//}