//package com.edexsoft.matrix.domain;
//
//import com.edexsoft.data.BaseEntity;
//
//public class User extends BaseEntity {
//	private static final long serialVersionUID = 1L;
//	
//	/**
//	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_user.account
//	 * @mbg.generated
//	 */
//	private String account;
//	/**
//	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_user.password
//	 * @mbg.generated
//	 */
//	private String password;
//	/**
//	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_user.nick_name
//	 * @mbg.generated
//	 */
//	private String nickName;
//	/**
//	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_user.audit_state
//	 * @mbg.generated
//	 */
//	private Integer auditState;
//	/**
//	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_user.desc
//	 * @mbg.generated
//	 */
//	private String desc;
//	/**
//	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_user.ext_1
//	 * @mbg.generated
//	 */
//	private String ext1;
//	/**
//	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_user.ext_2
//	 * @mbg.generated
//	 */
//	private String ext2;
//	/**
//	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_user.ext_3
//	 * @mbg.generated
//	 */
//	private String ext3;
//	/**
//	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_user.ext_4
//	 * @mbg.generated
//	 */
//	private String ext4;
//
//	/**
//	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_user.account
//	 * @return  the value of t_user.account
//	 * @mbg.generated
//	 */
//	public String getAccount() {
//		return account;
//	}
//
//	/**
//	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_user.account
//	 * @param account  the value for t_user.account
//	 * @mbg.generated
//	 */
//	public void setAccount(String account) {
//		this.account = account;
//	}
//
//	/**
//	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_user.password
//	 * @return  the value of t_user.password
//	 * @mbg.generated
//	 */
//	public String getPassword() {
//		return password;
//	}
//
//	/**
//	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_user.password
//	 * @param password  the value for t_user.password
//	 * @mbg.generated
//	 */
//	public void setPassword(String password) {
//		this.password = password;
//	}
//
//	/**
//	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_user.nick_name
//	 * @return  the value of t_user.nick_name
//	 * @mbg.generated
//	 */
//	public String getNickName() {
//		return nickName;
//	}
//
//	/**
//	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_user.nick_name
//	 * @param nickName  the value for t_user.nick_name
//	 * @mbg.generated
//	 */
//	public void setNickName(String nickName) {
//		this.nickName = nickName;
//	}
//
//	/**
//	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_user.audit_state
//	 * @return  the value of t_user.audit_state
//	 * @mbg.generated
//	 */
//	public Integer getAuditState() {
//		return auditState;
//	}
//
//	/**
//	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_user.audit_state
//	 * @param auditState  the value for t_user.audit_state
//	 * @mbg.generated
//	 */
//	public void setAuditState(Integer auditState) {
//		this.auditState = auditState;
//	}
//
//	/**
//	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_user.desc
//	 * @return  the value of t_user.desc
//	 * @mbg.generated
//	 */
//	public String getDesc() {
//		return desc;
//	}
//
//	/**
//	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_user.desc
//	 * @param desc  the value for t_user.desc
//	 * @mbg.generated
//	 */
//	public void setDesc(String desc) {
//		this.desc = desc;
//	}
//
//	/**
//	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_user.ext_1
//	 * @return  the value of t_user.ext_1
//	 * @mbg.generated
//	 */
//	public String getExt1() {
//		return ext1;
//	}
//
//	/**
//	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_user.ext_1
//	 * @param ext1  the value for t_user.ext_1
//	 * @mbg.generated
//	 */
//	public void setExt1(String ext1) {
//		this.ext1 = ext1;
//	}
//
//	/**
//	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_user.ext_2
//	 * @return  the value of t_user.ext_2
//	 * @mbg.generated
//	 */
//	public String getExt2() {
//		return ext2;
//	}
//
//	/**
//	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_user.ext_2
//	 * @param ext2  the value for t_user.ext_2
//	 * @mbg.generated
//	 */
//	public void setExt2(String ext2) {
//		this.ext2 = ext2;
//	}
//
//	/**
//	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_user.ext_3
//	 * @return  the value of t_user.ext_3
//	 * @mbg.generated
//	 */
//	public String getExt3() {
//		return ext3;
//	}
//
//	/**
//	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_user.ext_3
//	 * @param ext3  the value for t_user.ext_3
//	 * @mbg.generated
//	 */
//	public void setExt3(String ext3) {
//		this.ext3 = ext3;
//	}
//
//	/**
//	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_user.ext_4
//	 * @return  the value of t_user.ext_4
//	 * @mbg.generated
//	 */
//	public String getExt4() {
//		return ext4;
//	}
//
//	/**
//	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_user.ext_4
//	 * @param ext4  the value for t_user.ext_4
//	 * @mbg.generated
//	 */
//	public void setExt4(String ext4) {
//		this.ext4 = ext4;
//	}
//}